name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -v ./cmd/server
      - name: Test
        run: go test ./...
      - name: Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose
          docker-compose up -d redis
